### ISSUE TITLE
Crashed when clearing typehead cache.

### ISSUE THREAD

**Issue by quadbyte** [abenz1267/walker#138]
**Describe the bug**
Program seem to crash when using "Clear Typehead Cache" via  "walker -m commands"

**Version**
0.7.8

**Minimal Config**
Provide a minimal config to reproduce the bug.

**To Reproduce**
- walker -m commands
- choose Clear Typehead Cache

**Expected behavior**
Not crash.

**Desktop**
 - Arch Linux
 - Hyprland

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: closure error: unexpected panic caught: runtime error: invalid memory address or nil pointer dereference
	
	Closure added at:
		github.com/diamondburned/gotk4/pkg/gtk/v4.(*EventControllerKey).ConnectKeyPressed at /home/runner/go/pkg/mod/github.com/diamondburned/gotk4/pkg@v0.3.0/gtk/v4/gtk.go:52882
		github.com/abenz1267/walker/internal/ui.setupInteractions at /home/runner/work/walker/walker/internal/ui/interactions.go:80
		main.main.Activate.func5 at /home/runner/work/walker/walker/internal/ui/ui.go:134
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x99bba8]

goroutine 1 [running, locked to thread]:
github.com/diamondburned/gotk4/pkg/core/closure.(*FuncStack).Panicf(0xc0003a7da0, {0xce0f99, 0x1b}, {0xc00041b028, 0x1, 0x1})
	/home/runner/go/pkg/mod/github.com/diamondburned/gotk4/pkg@v0.3.0/core/closure/funcstack.go:104 +0x908
github.com/diamondburned/gotk4/pkg/core/closure.(*FuncStack).TryRepanic(0xc0003a7da0)
	/home/runner/go/pkg/mod/github.com/diamondburned/gotk4/pkg@v0.3.0/core/closure/funcstack.go:122 +0xbc
panic({0xaf9b20?, 0x12d3000?})
	/opt/hostedtoolcache/go/1.23.2/x64/src/runtime/panic.go:785 +0x132
github.com/abenz1267/walker/internal/ui.activateItem(0x0, 0x0, 0x0)
	/home/runner/work/walker/walker/internal/ui/interactions.go:396 +0x1c8
github.com/abenz1267/walker/internal/ui.handleGlobalKeysPressed(0x1319601?, 0xc00041ba50?, 0x766ee4?)
	/home/runner/work/walker/walker/internal/ui/interactions.go:251 +0x5af
github.com/diamondburned/gotk4/pkg/gtk/v4._gotk4_gtk4_EventControllerKey_ConnectKeyPressed(0x947145?, 0xff0d, 0x24, 0x0, 0x5?)
	/home/runner/go/pkg/mod/github.com/diamondburned/gotk4/pkg@v0.3.0/gtk/v4/gtk_export.go:5093 +0x87
github.com/diamondburned/gotk4/pkg/gio/v2._Cfunc_g_application_run(0x2f2b8960, 0x3, 0x2f2bccb0)
	_cgo_gotypes.go:12555 +0x4b
github.com/diamondburned/gotk4/pkg/gio/v2.(*Application).Run.func3(0x2f2b8960, 0x3, 0x2f2bccb0)
	/home/runner/go/pkg/mod/github.com/diamondburned/gotk4/pkg@v0.3.0/gio/v2/gio.go:36988 +0x67
github.com/diamondburned/gotk4/pkg/gio/v2.(*Application).Run(0xc0001ffd28, {0xc0001283c0, 0x3, 0x3})
	/home/runner/go/pkg/mod/github.com/diamondburned/gotk4/pkg@v0.3.0/gio/v2/gio.go:36988 +0x1f1
main.main()
	/home/runner/work/walker/walker/cmd/walker.go:241 +0x72a
```

**Comment by quadbyte** [comment]
Same crash with Reload Config.

**Comment by abenz1267** [comment]
fixed.
