### ISSUE TITLE
[0.9.{9,10}] Walker crashes with the following message 

### ISSUE THREAD

**Issue by IceDBorn** [abenz1267/walker#163]
```bash
1 error(s) decoding:

* 'builtins.applications.actions' expected a map, got 'bool'
panic: 1 error(s) decoding:
	
	* 'builtins.applications.actions' expected a map, got 'bool' [recovered]
	panic: closure error: unexpected panic caught: 1 error(s) decoding:
	
	* 'builtins.applications.actions' expected a map, got 'bool'
	
	Closure added at:
		main.main at ./walker.go:120
		runtime.main at runtime/proc.go:272
		runtime.goexit at runtime/asm_amd64.s:1700 [recovered]
	panic: closure error: unexpected panic caught: 1 error(s) decoding:
	
	* 'builtins.applications.actions' expected a map, got 'bool'
	
	Closure added at:
		main.main at ./walker.go:120
		runtime.main at runtime/proc.go:272
		runtime.goexit at runtime/asm_amd64.s:1700

goroutine 1 [running, locked to thread]:
github.com/diamondburned/gotk4/pkg/core/closure.(*FuncStack).TryRepanic(0xc00022e090)
	github.com/diamondburned/gotk4/pkg@v0.3.1/core/closure/funcstack.go:118 +0xe6
panic({0xbeadc0?, 0xc000311a80?})
	runtime/panic.go:785 +0x132
github.com/diamondburned/gotk4/pkg/core/closure.(*FuncStack).Panicf(0xc00022e030, {0xe49cdd, 0x1b}, {0xc000272ae0, 0x1, 0x1})
	github.com/diamondburned/gotk4/pkg@v0.3.1/core/closure/funcstack.go:104 +0x908
github.com/diamondburned/gotk4/pkg/core/closure.(*FuncStack).TryRepanic(0xc00022e030)
	github.com/diamondburned/gotk4/pkg@v0.3.1/core/closure/funcstack.go:122 +0xbc
panic({0xbeadc0?, 0xc000311a70?})
	runtime/panic.go:785 +0x132
log.Panic({0xc000272d08?, 0xbbd9e0?, 0xc00018db08?})
	log/log.go:432 +0x5a
github.com/abenz1267/walker/internal/config.Get({0x0?, 0xc00022e360?})
	github.com/abenz1267/walker/internal/config/config.go:308 +0x465
main.main.Activate.func5(0xc00021dcc8)
	github.com/abenz1267/walker/internal/ui/ui.go:84 +0x9c
reflect.Value.call({0xbedb80?, 0x1112ec0?, 0x56f171?}, {0xe3a903, 0x4}, {0xc00021dcb0, 0x1, 0xc0000a4640?})
	reflect/value.go:581 +0xca6
reflect.Value.Call({0xbedb80?, 0x1112ec0?, 0xdbd240?}, {0xc00021dcb0?, 0x1115480?, 0xd9949a0?})
	reflect/value.go:365 +0xb9
github.com/diamondburned/gotk4/pkg/core/glib._gotk4_goMarshal(0xd9b60a0, 0x0, 0x1, 0x7ffeed073440, 0xc0000061c0?, 0xd9b1a20)
	github.com/diamondburned/gotk4/pkg@v0.3.1/core/glib/glib.go:306 +0x978
github.com/diamondburned/gotk4/pkg/gio/v2._Cfunc_g_application_activate(0xd9b1a20)
	_cgo_gotypes.go:13549 +0x3f
github.com/diamondburned/gotk4/pkg/gio/v2.(*Application).Activate.func1(0xd9b1a20)
	github.com/diamondburned/gotk4/pkg@v0.3.1/gio/v2/gio.go:41449 +0x34
github.com/diamondburned/gotk4/pkg/gio/v2.(*Application).Activate(0xc00021dc80)
	github.com/diamondburned/gotk4/pkg@v0.3.1/gio/v2/gio.go:41449 +0x37
main.main.func3(0xc0001fc518)
	./walker.go:212 +0x8fd
github.com/diamondburned/gotk4/pkg/gio/v2._gotk4_gio2_Application_ConnectCommandLine(0xd9b1a20?, 0xda7f990, 0x1001?)
	github.com/diamondburned/gotk4/pkg@v0.3.1/gio/v2/gio_export.go:1841 +0x102
github.com/diamondburned/gotk4/pkg/gio/v2._Cfunc_g_application_run(0xd9b1a20, 0x3, 0xd9b6380)
	_cgo_gotypes.go:14100 +0x4b
github.com/diamondburned/gotk4/pkg/gio/v2.(*Application).Run.func3(0xd9b1a20, 0x3, 0xd9b6380)
	github.com/diamondburned/gotk4/pkg@v0.3.1/gio/v2/gio.go:42200 +0x67
github.com/diamondburned/gotk4/pkg/gio/v2.(*Application).Run(0xc00021dc80, {0xc0000242a0, 0x3, 0x3})
	github.com/diamondburned/gotk4/pkg@v0.3.1/gio/v2/gio.go:42200 +0x1f1
main.main()
	./walker.go:246 +0x72a
```

**Comment by IceDBorn** [comment]
I do not get this error using 0.9.8 or lower.

**Comment by abenz1267** [comment]
check the release notes:

> break: refactored applications module config for actions, added option to hide category

Correct way to configure actions from 0.9.10 forward will be:

```json
  "actions": {
        "enabled": true,
        "hide_category": false,
        "hide_without_query": true
      },
 ```

**Comment by IceDBorn** [comment]
I do not have a file though to configure anything. Just a style.css. @abenz1267

**Comment by abenz1267** [comment]
are you on nix?

**Comment by IceDBorn** [comment]
Yes, I'm using nix and I was just theming walker with home manager, that's why I forgot about config.json.

**Comment by IceDBorn** [comment]
Maybe I should just use the package's config.json using home manager. This way I won't have to delete the file if something changes in the future.
