### ISSUE TITLE
fatal error: concurrent map writes

### ISSUE THREAD

**Issue by varac** [abenz1267/walker#179]
**Describe the bug**
Sometimes walker breaks with a `fatal error: concurrent map writes`. 

**Version**
0.10.14

**Minimal Config**
This is my walker config:

```yaml
$ cat .config/walker/config.yaml 
# https://github.com/abenz1267/walker/wiki/Modules
builtins:
  websearch:
    entries:
      - name: Google
        url: https://www.google.com/search?q=%TERM%
        prefix: "go"
      - name: DuckDuckGo
        switcher_only: true
        url: https://duckduckgo.com/?q=%TERM%
        prefix: "ddg"
      - name: Debian packages
        prefix: "deb"
        switcher_only: true
        url: https://packages.debian.org/search?keywords=%TERM%
      - name: Arch packages
        prefix: "arch"
        switcher_only: true
        url: https://archlinux.org/packages/?q=%TERM%
      - name: AUR packages
        prefix: "aur"
        switcher_only: true
        url: https://aur.archlinux.org/packages?K=%TERM%
    icon: applications-internet
    name: websearch
    placeholder: Websearch
    weight: 5

force_keyboard_focus: true

plugins:
  - name: rbw
    prefix: !
    src_once: /home/varac/bin/custom/rbw_list_cached.sh
    cmd: rbw get $(echo "%RESULT%") | tr -d '\n' | wl-copy
```

**To Reproduce**
I can't reproduce consistently, it happens randomly.
Last time this bug was triggered when I wanted to start firefox: 

* invoke walker
* press `fi`
* walker crashes

**Expected behavior**
Walker should not crash.

**Screenshots**
-

**Desktop**

- OS (Arch, Nix etc): Manjaro Sway edition
- DE (Plasma, Hyprland etc. ): Sway

**Additional context**

<details>
<summary>Click to show log</summary>

```
Dez 12 20:38:02 zancas sway[1620]: 51:24:50.876 [ERROR] [wlr] [backend/drm/atomic.c:79] connector eDP-1: Atomic commit failed: Device or resource busy
Dez 12 20:38:02 zancas sway[1620]: 51:24:50.876 [ERROR] [sway/desktop/output.c:317] Page-flip failed on output eDP-1
Dez 12 20:38:02 zancas sway[1620]: 51:24:50.910 [ERROR] [wlr] [backend/drm/atomic.c:79] connector eDP-1: Atomic commit failed: Device or resource busy
Dez 12 20:38:02 zancas sway[1620]: 51:24:50.910 [ERROR] [sway/desktop/output.c:317] Page-flip failed on output eDP-1
Dez 12 20:38:02 zancas sway[1620]: 51:24:50.943 [ERROR] [wlr] [backend/drm/atomic.c:79] connector eDP-1: Atomic commit failed: Device or resource busy
Dez 12 20:38:02 zancas sway[1620]: 51:24:50.943 [ERROR] [sway/desktop/output.c:317] Page-flip failed on output eDP-1
Dez 12 20:38:02 zancas sway[1620]: 51:24:50.976 [ERROR] [wlr] [backend/drm/atomic.c:79] connector eDP-1: Atomic commit failed: Device or resource busy
Dez 12 20:38:02 zancas sway[1620]: 51:24:50.976 [ERROR] [sway/desktop/output.c:317] Page-flip failed on output eDP-1
Dez 12 20:38:02 zancas sway[1620]: 51:24:51.010 [ERROR] [wlr] [backend/drm/atomic.c:79] connector eDP-1: Atomic commit failed: Device or resource busy
Dez 12 20:38:02 zancas sway[1620]: 51:24:51.010 [ERROR] [sway/desktop/output.c:317] Page-flip failed on output eDP-1
Dez 12 20:38:02 zancas sway[1620]: 51:24:51.043 [ERROR] [wlr] [backend/drm/atomic.c:79] connector eDP-1: Atomic commit failed: Device or resource busy
Dez 12 20:38:02 zancas sway[1620]: 51:24:51.043 [ERROR] [sway/desktop/output.c:317] Page-flip failed on output eDP-1
Dez 12 20:38:02 zancas sway[1620]: 51:24:51.310 [ERROR] [wlr] [backend/drm/atomic.c:79] connector eDP-1: Atomic commit failed: Device or resource busy
Dez 12 20:38:02 zancas sway[1620]: 51:24:51.310 [ERROR] [sway/desktop/output.c:317] Page-flip failed on output eDP-1
Dez 12 20:38:02 zancas sway[1620]: 51:24:51.326 [ERROR] [wlr] [backend/drm/atomic.c:79] connector eDP-1: Atomic commit failed: Device or resource busy
Dez 12 20:38:02 zancas sway[1620]: 51:24:51.326 [ERROR] [sway/desktop/output.c:317] Page-flip failed on output eDP-1
Dez 12 20:38:02 zancas sway[636930]: fatal error: concurrent map writes
Dez 12 20:38:02 zancas sway[636930]: goroutine 69 [running]:
Dez 12 20:38:02 zancas sway[636930]: github.com/abenz1267/walker/internal/modules/windows.(*Windows).GetIcons.func1({0xc0002db5c0, 0x35}, {0x1223e08, 0xc000635400}, {0x35?, 0xc0002db5c0?})
Dez 12 20:38:02 zancas sway[636930]:         /home/runner/work/walker/walker/internal/modules/windows/windows.go:79 +0x2b9
Dez 12 20:38:02 zancas sway[636930]: path/filepath.walkDir({0xc0002db5c0, 0x35}, {0x1223e08, 0xc000635400}, 0xc0001cfc00)
Dez 12 20:38:02 zancas sway[636930]:         /opt/hostedtoolcache/go/1.23.4/x64/src/path/filepath/path.go:310 +0x50
Dez 12 20:38:02 zancas sway[636930]: path/filepath.walkDir({0xe9727e, 0x17}, {0x1223e78, 0xc0003ac050}, 0xc0001cfc00)
Dez 12 20:38:02 zancas sway[636930]:         /opt/hostedtoolcache/go/1.23.4/x64/src/path/filepath/path.go:332 +0x285
Dez 12 20:38:02 zancas sway[636930]: path/filepath.WalkDir({0xe9727e, 0x17}, 0xc0001cfc00)
Dez 12 20:38:02 zancas sway[636930]:         /opt/hostedtoolcache/go/1.23.4/x64/src/path/filepath/path.go:400 +0x75
Dez 12 20:38:02 zancas sway[636930]: github.com/abenz1267/walker/internal/modules/windows.(*Windows).GetIcons(0xc000502300)
Dez 12 20:38:02 zancas sway[636930]:         /home/runner/work/walker/walker/internal/modules/windows/windows.go:60 +0x11d
Dez 12 20:38:02 zancas sway[636930]: github.com/abenz1267/walker/internal/modules/windows.(*Windows).SetupData(0xc000502300, 0xc000265008?)
Dez 12 20:38:02 zancas sway[636930]:         /home/runner/work/walker/walker/internal/modules/windows/windows.go:44 +0x65
Dez 12 20:38:02 zancas sway[636930]: github.com/abenz1267/walker/internal/ui.processAsync({0xc00011cd5c, 0x1})
Dez 12 20:38:02 zancas sway[636930]:         /home/runner/work/walker/walker/internal/ui/interactions.go:878 +0x697
Dez 12 20:38:02 zancas sway[636930]: created by github.com/abenz1267/walker/internal/ui.process in goroutine 68
Dez 12 20:38:02 zancas sway[636930]:         /home/runner/work/walker/walker/internal/ui/interactions.go:727 +0x1a5
Dez 12 20:38:02 zancas sway[636930]: goroutine 1 [syscall, locked to thread]:
Dez 12 20:38:02 zancas sway[636930]: github.com/diamondburned/gotk4/pkg/gio/v2._Cfunc_g_application_run(0x2adf91d0, 0x1, 0x2adffba0)
Dez 12 20:38:02 zancas sway[636930]:         _cgo_gotypes.go:14091 +0x4b
Dez 12 20:38:02 zancas sway[636930]: github.com/diamondburned/gotk4/pkg/gio/v2.(*Application).Run.func3(0x2adf91d0, 0x1, 0x2adffba0)
Dez 12 20:38:02 zancas sway[636930]:         /home/runner/go/pkg/mod/github.com/diamondburned/gotk4/pkg@v0.3.1/gio/v2/gio.go:42200 +0x67
Dez 12 20:38:02 zancas sway[636930]: github.com/diamondburned/gotk4/pkg/gio/v2.(*Application).Run(0xc0001361b0, {0xc000196160, 0x1, 0x1})
Dez 12 20:38:02 zancas sway[636930]:         /home/runner/go/pkg/mod/github.com/diamondburned/gotk4/pkg@v0.3.1/gio/v2/gio.go:42200 +0x1f1
Dez 12 20:38:02 zancas sway[636930]: main.main()
Dez 12 20:38:02 zancas sway[636930]:         /home/runner/work/walker/walker/cmd/walker.go:265 +0x845
Dez 12 20:38:02 zancas sway[636930]: goroutine 17 [syscall, locked to thread]:
Dez 12 20:38:02 zancas sway[636930]: runtime.goexit({})
Dez 12 20:38:02 zancas sway[636930]:         /opt/hostedtoolcache/go/1.23.4/x64/src/runtime/asm_amd64.s:1700 +0x1
Dez 12 20:38:02 zancas sway[636930]: goroutine 10 [runnable]:
Dez 12 20:38:02 zancas sway[636930]: github.com/abenz1267/walker/internal/modules.Runner.Entries({{{0x0, {0x0, 0x0, 0x0}, 0x0, 0x1, {0xc0001685d0, 0x12}, 0x0, 0x0, ...}, ...}, ...}, ...)
Dez 12 20:38:02 zancas sway[636930]:         /home/runner/work/walker/walker/internal/modules/runner.go:95 +0x2e5
Dez 12 20:38:02 zancas sway[636930]: github.com/abenz1267/walker/internal/ui.processAsync.func3(0xc000282040?, {0xc00028201c, 0x2}, {0x1226518, 0xc0000dea00})
Dez 12 20:38:02 zancas sway[636930]:         /home/runner/work/walker/walker/internal/ui/interactions.go:890 +0xdb
Dez 12 20:38:02 zancas sway[636930]: created by github.com/abenz1267/walker/internal/ui.processAsync in goroutine 72
Dez 12 20:38:02 zancas sway[636930]:         /home/runner/work/walker/walker/internal/ui/interactions.go:881 +0x7c5
Dez 12 20:38:02 zancas sway[636930]: goroutine 51 [select]:
Dez 12 20:38:02 zancas sway[636930]: github.com/abenz1267/walker/internal/modules.(*Applications).RunWm(0xc0000ae480)
Dez 12 20:38:02 zancas sway[636930]:         /home/runner/work/walker/walker/internal/modules/applications.go:136 +0x13c
Dez 12 20:38:02 zancas sway[636930]: created by github.com/abenz1267/walker/internal/modules.(*Applications).SetupData in goroutine 26
Dez 12 20:38:02 zancas sway[636930]:         /home/runner/work/walker/walker/internal/modules/applications.go:63 +0xf9
Dez 12 20:38:02 zancas sway[636930]: goroutine 27 [IO wait]:
Dez 12 20:38:02 zancas sway[636930]: internal/poll.runtime_pollWait(0x7d2d90ec6410, 0x72)
Dez 12 20:38:02 zancas sway[636930]:         /opt/hostedtoolcache/go/1.23.4/x64/src/runtime/netpoll.go:351 +0x85
Dez 12 20:38:02 zancas sway[636930]: internal/poll.(*pollDesc).wait(0xc0000b8700?, 0xc0003061e0?, 0x0)
Dez 12 20:38:02 zancas sway[636930]:         /opt/hostedtoolcache/go/1.23.4/x64/src/internal/poll/fd_poll_runtime.go:84 +0x27
Dez 12 20:38:02 zancas sway[636930]: internal/poll.(*pollDesc).waitRead(...)
Dez 12 20:38:02 zancas sway[636930]:         /opt/hostedtoolcache/go/1.23.4/x64/src/internal/poll/fd_poll_runtime.go:89
Dez 12 20:38:02 zancas sway[636930]: internal/poll.(*FD).ReadMsg(0xc0000b8700, {0xc0003061e0, 0x8, 0x44}, {0xc000190d00, 0x18, 0x100}, 0x40000000)
Dez 12 20:38:02 zancas sway[636930]:         /opt/hostedtoolcache/go/1.23.4/x64/src/internal/poll/fd_unix.go:302 +0x385
Dez 12 20:38:02 zancas sway[636930]: net.(*netFD).readMsg(0xc0000b8700, {0xc0003061e0?, 0x4?, 0xc000104fc0?}, {0xc000190d00?, 0x0?, 0xc00017edd0?}, 0x54a19d?)
Dez 12 20:38:02 zancas sway[636930]:         /opt/hostedtoolcache/go/1.23.4/x64/src/net/fd_posix.go:78 +0x31
Dez 12 20:38:02 zancas sway[636930]: net.(*UnixConn).readMsg(0xc00019c738, {0xc0003061e0?, 0xc22d60?, 0x0?}, {0xc000190d00?, 0xc00017edf8?, 0xa96ede?})
Dez 12 20:38:02 zancas sway[636930]:         /opt/hostedtoolcache/go/1.23.4/x64/src/net/unixsock_posix.go:115 +0x45
Dez 12 20:38:02 zancas sway[636930]: net.(*UnixConn).ReadMsgUnix(0xc00019c738, {0xc0003061e0?, 0xc000013b60?, 0xd32868?}, {0xc000190d00?, 0x54a19d?, 0xbe8f11?})
Dez 12 20:38:02 zancas sway[636930]:         /opt/hostedtoolcache/go/1.23.4/x64/src/net/unixsock.go:143 +0x36
Dez 12 20:38:02 zancas sway[636930]: github.com/neurlang/wayland/wl.(*Context).readEvent(0xc000134dc0)
Dez 12 20:38:02 zancas sway[636930]:         /home/runner/go/pkg/mod/github.com/neurlang/wayland@v0.1.36/wl/event.go:49 +0xa9
Dez 12 20:38:02 zancas sway[636930]: github.com/neurlang/wayland/wl.(*Context).run(0xc000134dc0, 0x0)
Dez 12 20:38:02 zancas sway[636930]:         /home/runner/go/pkg/mod/github.com/neurlang/wayland@v0.1.36/wl/context.go:165 +0x2d
Dez 12 20:38:02 zancas sway[636930]: github.com/neurlang/wayland/wl.(*Context).Run(...)
Dez 12 20:38:02 zancas sway[636930]:         /home/runner/go/pkg/mod/github.com/neurlang/wayland@v0.1.36/wl/context.go:147
Dez 12 20:38:02 zancas sway[636930]: github.com/abenz1267/walker/internal/modules/windows/wlr.StartWM(0x0?, 0x0?)
Dez 12 20:38:02 zancas sway[636930]:         /home/runner/work/walker/walker/internal/modules/windows/wlr/wm.go:64 +0x17e
Dez 12 20:38:02 zancas sway[636930]: created by github.com/abenz1267/walker/internal/modules.(*Applications).RunWm in goroutine 51
Dez 12 20:38:02 zancas sway[636930]:         /home/runner/work/walker/walker/internal/modules/applications.go:133 +0xb7
Dez 12 20:38:02 zancas sway[636930]: goroutine 72 [runnable]:
Dez 12 20:38:02 zancas sway[636930]: bufio.(*Scanner).Scan(0xc000537870)
Dez 12 20:38:02 zancas sway[636930]:         /opt/hostedtoolcache/go/1.23.4/x64/src/bufio/scan.go:209 +0x379
Dez 12 20:38:02 zancas sway[636930]: github.com/abenz1267/walker/internal/modules/windows.(*Windows).GetIcons.func1({0xc00002a510, 0x24}, {0x1223e08, 0xc0004cdc00}, {0x24?, 0xc00002a510?})
Dez 12 20:38:02 zancas sway[636930]:         /home/runner/work/walker/walker/internal/modules/windows/windows.go:77 +0x279
Dez 12 20:38:02 zancas sway[636930]: path/filepath.walkDir
Dez 12 20:38:02 zancas sway[1620]: 51:24:51.343 [ERROR] [wlr] [backend/drm/atomic.c:79] connector eDP-1: Atomic commit failed: Device or resource busy
Dez 12 20:38:02 zancas sway[1620]: 51:24:51.343 [ERROR] [sway/desktop/output.c:317] Page-flip failed on output eDP-1
```
</details>

**Comment by abenz1267** [comment]
Thanks for reporting, should be fixed now.
