### ISSUE TITLE
gtk-layer-shell not supported.

### ISSUE THREAD

**Issue by vinoff** [abenz1267/walker#183]
I installed walker-bin from AUR. I am using x11, though.. I wonder if walker supports x11?

I get an error when I try running it for the first time:

```
> walker
gtk-layer-shell not supported
panic: gtk-layer-shell not supported
         [recovered]
        panic: closure error: unexpected panic caught: gtk-layer-shell not supported


        Closure added at:
                main.main at /home/runner/work/walker/walker/cmd/walker.go:138
                runtime.main at /opt/hostedtoolcache/go/1.23.4/x64/src/runtime/proc.go:272
                runtime.goexit at /opt/hostedtoolcache/go/1.23.4/x64/src/runtime/asm_amd64.s:1700 [recovered]
        panic: closure error: unexpected panic caught: gtk-layer-shell not supported


        Closure added at:
                main.main at /home/runner/work/walker/walker/cmd/walker.go:138
                runtime.main at /opt/hostedtoolcache/go/1.23.4/x64/src/runtime/proc.go:272
                runtime.goexit at /opt/hostedtoolcache/go/1.23.4/x64/src/runtime/asm_amd64.s:1700

goroutine 1 [running, locked to thread]:
github.com/diamondburned/gotk4/pkg/core/closure.(*FuncStack).TryRepanic(0xc00024a510)
        /home/runner/go/pkg/mod/github.com/diamondburned/gotk4/pkg@v0.3.1/core/closure/funcstack.go:118 +0xe6
panic({0xc2e8c0?, 0xc000459530?})
        /opt/hostedtoolcache/go/1.23.4/x64/src/runtime/panic.go:785 +0x132
github.com/diamondburned/gotk4/pkg/core/closure.(*FuncStack).Panicf(0xc00024a4b0, {0xe9c5e3, 0x1b}, {0xc00043eb50, 0x1, 0x1})
        /home/runner/go/pkg/mod/github.com/diamondburned/gotk4/pkg@v0.3.1/core/closure/funcstack.go:104 +0x908
github.com/diamondburned/gotk4/pkg/core/closure.(*FuncStack).TryRepanic(0xc00024a4b0)
        /home/runner/go/pkg/mod/github.com/diamondburned/gotk4/pkg@v0.3.1/core/closure/funcstack.go:122 +0xbc
panic({0xc2e8c0?, 0xc000459520?})
        /opt/hostedtoolcache/go/1.23.4/x64/src/runtime/panic.go:785 +0x132
log.Panicln({0xc00043eca0?, 0xc0004640c0?, 0xc000464080?})
        /opt/hostedtoolcache/go/1.23.4/x64/src/log/log.go:446 +0x5a
github.com/abenz1267/walker/internal/ui.setupLayerShell()
        /home/runner/work/walker/walker/internal/ui/ui.go:782 +0x69
main.main.Activate.func5(0xc000012030)
        /home/runner/work/walker/walker/internal/ui/ui.go:147 +0x5ed
reflect.Value.call({0xc318c0?, 0x1167eb0?, 0x560c51?}, {0xe8b838, 0x4}, {0xc000012018, 0x1, 0xc000164700?})
        /opt/hostedtoolcache/go/1.23.4/x64/src/reflect/value.go:581 +0xca6
reflect.Value.Call({0xc318c0?, 0x1167eb0?, 0xe0de40?}, {0xc000012018?, 0x116a4d0?, 0x9711490?})
        /opt/hostedtoolcache/go/1.23.4/x64/src/reflect/value.go:365 +0xb9
github.com/diamondburned/gotk4/pkg/core/glib._gotk4_goMarshal(0x9812840, 0x0, 0x1, 0x7fff4ee24a10, 0xc0000061c0?, 0x980c150)
        /home/runner/go/pkg/mod/github.com/diamondburned/gotk4/pkg@v0.3.1/core/glib/glib.go:306 +0x978
github.com/diamondburned/gotk4/pkg/gio/v2._Cfunc_g_application_activate(0x980c150)
        _cgo_gotypes.go:13540 +0x3f
github.com/diamondburned/gotk4/pkg/gio/v2.(*Application).Activate.func1(0x980c150)
        /home/runner/go/pkg/mod/github.com/diamondburned/gotk4/pkg@v0.3.1/gio/v2/gio.go:41449 +0x34
github.com/diamondburned/gotk4/pkg/gio/v2.(*Application).Activate(0xc000239d28)
        /home/runner/go/pkg/mod/github.com/diamondburned/gotk4/pkg@v0.3.1/gio/v2/gio.go:41449 +0x37
main.main.func3(0xc000054010)
        /home/runner/work/walker/walker/cmd/walker.go:230 +0x8fd
github.com/diamondburned/gotk4/pkg/gio/v2._gotk4_gio2_Application_ConnectCommandLine(0xc000035a20?, 0x9814320, 0x99c35e0?)
        /home/runner/go/pkg/mod/github.com/diamondburned/gotk4/pkg@v0.3.1/gio/v2/gio_export.go:1841 +0x102
github.com/diamondburned/gotk4/pkg/gio/v2._Cfunc_g_application_run(0x980c150, 0x1, 0x9812b20)
        _cgo_gotypes.go:14091 +0x4b
github.com/diamondburned/gotk4/pkg/gio/v2.(*Application).Run.func3(0x980c150, 0x1, 0x9812b20)
        /home/runner/go/pkg/mod/github.com/diamondburned/gotk4/pkg@v0.3.1/gio/v2/gio.go:42200 +0x67
github.com/diamondburned/gotk4/pkg/gio/v2.(*Application).Run(0xc000239d28, {0xc00011e160, 0x1, 0x1})
        /home/runner/go/pkg/mod/github.com/diamondburned/gotk4/pkg@v0.3.1/gio/v2/gio.go:42200 +0x1f1
main.main()
        /home/runner/work/walker/walker/cmd/walker.go:265 +0x845
```

I do have gtk4-layer-shell:

```
> pacman -Ss gtk4-layer-shell
extra/gtk4-layer-shell 1.0.4-1 [installed]
    Library to create panels and other desktop components for Wayland
```

**Comment by abenz1267** [comment]
Wayland only.
