### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by donovanglover** [abenz1267/walker#2]
<details>

<summary>Getting this runtime error after packaging walker for Nix/NixOS.</summary>

```go
startup time: 77.806913mspanic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: closure error: unexpected panic caught: runtime error: invalid memory address or nil pointer dereference

Closure added at:
	main.main at github.com/abenz1267/walker/main.go:81
	runtime.main at runtime/proc.go:271
	runtime.goexit at runtime/asm_amd64.s:1695
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x5ce633]

goroutine 1 [running, locked to thread]:
github.com/diamondburned/gotk4/pkg/core/closure.(*FuncStack).Panicf(0xc0000aa390, {0xa845b1, 0x1b}, {0xc000040760, 0x1, 0x1})
	github.com/diamondburned/gotk4/pkg@v0.2.2/core/closure/funcstack.go:104 +0x908
github.com/diamondburned/gotk4/pkg/core/closure.(*FuncStack).TryRepanic(0xc0000aa390)
	github.com/diamondburned/gotk4/pkg@v0.2.2/core/closure/funcstack.go:122 +0xc5
panic({0x8ee540?, 0xe72230?})
	runtime/panic.go:770 +0x132
github.com/abenz1267/walker/processors.parse.func1({0xa82d7e, 0x18}, {0x0?, 0x0?}, {0x4e8d85?, 0x18?})
	github.com/abenz1267/walker/processors/applications.go:93 +0x73
path/filepath.Walk({0xa82d7e, 0x18}, 0xc000040b88)
	path/filepath/path.go:558 +0x4a
github.com/abenz1267/walker/processors.parse()
	github.com/abenz1267/walker/processors/applications.go:92 +0x23a
github.com/abenz1267/walker/processors.GetApplications()
	github.com/abenz1267/walker/processors/applications.go:37 +0x25
main.setupInteractions()
	github.com/abenz1267/walker/interactions.go:32 +0x78
main.activate(0xc00012e018)
	github.com/abenz1267/walker/main.go:153 +0x41f
reflect.Value.call({0x8b5b40?, 0xa921d0?, 0x18?}, {0xa7b398, 0x4}, {0xc00012e000, 0x1, 0xc00012e000?})
	reflect/value.go:596 +0xce5
reflect.Value.Call({0x8b5b40?, 0xa921d0?, 0xa0b000?}, {0xc00012e000?, 0x10?, 0xe8d1e0?})
	reflect/value.go:380 +0xb9
github.com/diamondburned/gotk4/pkg/core/glib._gotk4_goMarshal(0x2ba5e20, 0x0, 0x1, 0x7ffd88db4880, 0x4df985?, 0x2ba4550)
	github.com/diamondburned/gotk4/pkg@v0.2.2/core/glib/glib.go:294 +0x998
github.com/diamondburned/gotk4/pkg/gio/v2._Cfunc_g_application_run(0x2ba4550, 0x1, 0x2ba5f50)
	_cgo_gotypes.go:13795 +0x4b
github.com/diamondburned/gotk4/pkg/gio/v2.(*Application).Run.func3(0x2ba4550, 0x1, 0x2ba5f50)
	github.com/diamondburned/gotk4/pkg@v0.2.2/gio/v2/gio.go:41611 +0x67
github.com/diamondburned/gotk4/pkg/gio/v2.(*Application).Run(0xc0001bd4b8, {0xc000016060, 0x1, 0x1})
	github.com/diamondburned/gotk4/pkg@v0.2.2/gio/v2/gio.go:41611 +0x1f1
main.main()
	github.com/abenz1267/walker/main.go:83 +0x27e
```

</details>

Steps to reproduce: [`nix run github:donovanglover/nixpkgs/walker#walker`](https://github.com/donovanglover/nixpkgs/blob/walker/pkgs/by-name/wa/walker/package.nix)

**Comment by donovanglover** [comment]
It works now, thanks!
